// The example trip: readable by anyone, writable by no one, real trips still private.
const h = require('./harness.js');
h.install();
process.env.IDENTITY_SESSION_SECRET = 'identity-secret-abcdefghijklmn';
process.env.SESSION_SECRET = 'trip-secret-abcdefghijklmnop';
process.env.FIRESTORE_DATABASE_ID = 'trip-planner'; process.env.IDENTITY_DATABASE_ID = 'identity';
process.env.GOOGLE_CLOUD_PROJECT = 'test'; process.env.ADMIN_EMAIL = 'boss@example.com';
process.env.ANTHROPIC_API_KEY = 'sk-ant-test'; process.env.PORT = '9211';
require(require('path').join(__dirname, '..', 'server.js'));
const B = 'http://127.0.0.1:9211';
let pass = 0, fail = 0;
const ok = (n, c, x) => { if (c) { pass++; console.log('PASS  ' + n); } else { fail++; console.log('FAIL  ' + n + (x ? '  <- ' + x : '')); } };
const J = { 'content-type': 'application/json' };
const post = (p, b, c) => fetch(B + p, { method: 'POST', headers: c ? { ...J, cookie: c } : J, body: JSON.stringify(b) });
const jar = (r) => (r.headers.getSetCookie() || []).map((c) => c.split(';')[0]).join('; ');
(async () => {
  await new Promise((r) => setTimeout(r, 900));
  let r = await fetch(B + '/api/trips/demo'); const trip = await r.json();
  ok('anyone can read the example trip', r.status === 200 && trip.demo === true && trip.days.length === 5, String(r.status));
  ok('it is cacheable', /max-age/.test(r.headers.get('cache-control') || ''));
  r = await fetch(B + '/api/trips/demo/messages'); const msgs = await r.json();
  ok('...and its chat', r.status === 200 && msgs.length === 3 && msgs[1].proposedChange);
  r = await fetch(B + '/api/trips/demo/watches'); const ws = await r.json();
  ok('...and its watches, with history', r.status === 200 && ws.length === 2 && ws[0].history.length === 4);
  r = await fetch(B + '/api/trips');
  ok('the real trips list is still sign-in only', r.status === 401, String(r.status));
  r = await post('/api/trips/demo/chat', { question: 'hi' });
  ok('signed out, writing to the example is a 401', r.status === 401, String(r.status));
  const user = jar(await post('/api/auth/register', { email: 'u@example.com', password: 'a-long-password-1' }));
  r = await post('/api/trips/demo/lock', {}, user); const b = await r.json();
  ok('signed in, writing to the example is a 403 that says so', r.status === 403 && b.demo === true, JSON.stringify(b));
  r = await post('/api/trips/demo/watches', { kind: 'flight', label: 'x' }, user);
  ok('...for every write route', r.status === 403, String(r.status));
  r = await post('/api/trips/demo/schedule/apply', { days: trip.days }, user);
  ok('...including the itinerary', r.status === 403, String(r.status));
  r = await fetch(B + '/api/trips/demo', { headers: { cookie: user } });
  ok('a signed-in user can still read it', r.status === 200);
  // Copying the example into an account.
  r = await post('/api/trips/demo/copy', {});
  ok('copying needs a session', r.status === 401, String(r.status));
  r = await post('/api/trips/demo/copy', {}, user);
  const copy = await r.json();
  ok('a signed-in user can copy the example', r.status === 200 && copy.id, JSON.stringify(copy));
  r = await fetch(B + '/api/trips/' + copy.id, { headers: { cookie: user } });
  const mine = await r.json();
  ok('the copy is theirs, and editable', r.status === 200 && mine.demo !== true);
  ok('...it arrives in planning, not locked', mine.status === 'planning', mine.status);
  ok('...with the itinerary', Array.isArray(mine.days) && mine.days.length === 5, String((mine.days || []).length));
  ok('...and remembers where it came from', mine.copiedFrom === 'demo');
  r = await fetch(B + '/api/trips/' + copy.id + '/watches', { headers: { cookie: user } });
  const copiedWatches = await r.json();
  ok('...and the watches came too', copiedWatches.length === 2, String(copiedWatches.length));
  ok('...with their history left behind', copiedWatches.every((w) => !w.history || !w.history.length));
  r = await post('/api/trips/' + copy.id + '/lock', {}, user);
  ok('the copy is writable, unlike the example', r.status === 200, String(r.status));

  r = await fetch(B + '/healthz');
  ok('frame-ancestors is set for the landing page', /frame-ancestors[^;]*strongtechnicalconsulting\.com/.test(r.headers.get('content-security-policy') || ''), r.headers.get('content-security-policy'));
  console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0);
})();
